[package]
name = "mtg_engine_core"
version = "0.1.0"
authors = ["Joe Roberts <josephroberts11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
